"""empty message

Revision ID: 0ec30cfc29f2
Revises: d591bb0060b8
Create Date: 2021-06-05 21:24:13.979371

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0ec30cfc29f2'
down_revision = 'd591bb0060b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('requested_time', sa.BigInteger(), nullable=False),
    sa.Column('arrival_time', sa.BigInteger(), nullable=False),
    sa.Column('time_difference', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_log')
    # ### end Alembic commands ###
