"""empty message

Revision ID: 17d0a0b80cac
Revises: 5f4e4f9506b5
Create Date: 2021-05-15 22:17:36.981365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d0a0b80cac'
down_revision = '5f4e4f9506b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_photos_original_datetime'), 'photos', ['original_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_original_datetime'), table_name='photos')
    # ### end Alembic commands ###
