"""empty message

Revision ID: 20c466e4ded0
Revises: 17d0a0b80cac
Create Date: 2021-05-16 20:20:41.914988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c466e4ded0'
down_revision = '17d0a0b80cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('md5', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'md5')
    # ### end Alembic commands ###
