"""empty message

Revision ID: 226374b9ec26
Revises: 0a6db29ff128
Create Date: 2021-05-08 22:56:54.938525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226374b9ec26'
down_revision = '0a6db29ff128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
