"""empty message

Revision ID: 38645a4a1f77
Revises: 20c466e4ded0
Create Date: 2021-05-16 20:23:16.850935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38645a4a1f77'
down_revision = '20c466e4ded0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'photos', ['md5'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='unique')
    # ### end Alembic commands ###
