"""empty message

Revision ID: 52f89e118d41
Revises: c986894e1ba1
Create Date: 2021-05-15 00:59:15.434762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f89e118d41'
down_revision = 'c986894e1ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('original_filename', sa.String(), nullable=False))
    op.add_column('photos', sa.Column('original_datetime', sa.DateTime(), nullable=False))
    op.add_column('photos', sa.Column('original_make', sa.String(), nullable=True))
    op.add_column('photos', sa.Column('original_model', sa.String(), nullable=True))
    op.add_column('photos', sa.Column('original_width', sa.Integer(), nullable=False))
    op.add_column('photos', sa.Column('original_height', sa.Integer(), nullable=False))
    op.add_column('photos', sa.Column('new_filename', sa.String(), nullable=False))
    op.add_column('photos', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('photos', sa.Column('longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'longitude')
    op.drop_column('photos', 'latitude')
    op.drop_column('photos', 'new_filename')
    op.drop_column('photos', 'original_height')
    op.drop_column('photos', 'original_width')
    op.drop_column('photos', 'original_model')
    op.drop_column('photos', 'original_make')
    op.drop_column('photos', 'original_datetime')
    op.drop_column('photos', 'original_filename')
    # ### end Alembic commands ###
