"""empty message

Revision ID: 875a2bf9ffda
Revises: 38645a4a1f77
Create Date: 2021-05-16 20:32:41.898560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875a2bf9ffda'
down_revision = '38645a4a1f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photos_md5_key', 'photos', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('photos_md5_key', 'photos', ['md5'])
    # ### end Alembic commands ###
