"""empty message

Revision ID: a16a34fb196a
Revises: d53afe4c4f56
Create Date: 2021-05-23 23:40:42.416685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16a34fb196a'
down_revision = 'd53afe4c4f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('original_filesize', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'original_filesize')
    # ### end Alembic commands ###
