"""empty message

Revision ID: a677504d5211
Revises: 226374b9ec26
Create Date: 2021-05-08 23:19:27.921987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a677504d5211'
down_revision = '226374b9ec26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
