"""empty message

Revision ID: d591bb0060b8
Revises: cb1fc2615489
Create Date: 2021-06-03 22:00:44.944838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd591bb0060b8'
down_revision = 'cb1fc2615489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'login_log', ['id'])
    op.add_column('photos', sa.Column('duration', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'duration')
    op.drop_constraint(None, 'login_log', type_='unique')
    # ### end Alembic commands ###
