"""empty message

Revision ID: f7cbfe4e04e7
Revises: 0ec30cfc29f2
Create Date: 2021-09-05 04:19:33.924711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cbfe4e04e7'
down_revision = '0ec30cfc29f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'request_log', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request_log', type_='unique')
    op.drop_table('feedback')
    # ### end Alembic commands ###
